CC	= gcc
CXX	= g++
CFLAGS	= -g -rdynamic -O0 -Wall -I./src/
CXXFLAGS= -g -rdynamic -O0 -Wall -I./src/
LD	= gcc
LDFLAGS	= -pthread
AR	= ar
ARFLAGS	=
RANLIB	= ranlib
RM	= rm
ECHO	= echo

SHELL	= /bin/bash

BUILDDIR=./build
