CC	= gcc
CXX	= g++
CFLAGS	= -g -rdynamic -O0 -Wall
CXXFLAGS= -g -rdynamic -O0 -Wall
LD	= gcc
LDFLAGS	= -lpthread
AR	= ar
ARFLAGS	=
RANLIB	= ranlib
RM	= rm
ECHO	= echo

SHELL	= /bin/bash

BUILDDIR=./build
